{{- $appSecretName := include "journiv.appSecretName" . -}}
{{- $postgresSecretName := include "journiv.postgresSecretName" . -}}
{{- $appSecretValue := include "journiv.appSecretValue" . -}}
{{- $postgresPasswordValue := include "journiv.postgresPasswordValue" . -}}
{{- if not .Values.config.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appSecretName }}
  labels:
    app: journiv
type: Opaque
stringData:
  SECRET_KEY: {{ $appSecretValue | quote }}
{{ end }}
{{- if not .Values.config.postgres.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $postgresSecretName }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ $postgresPasswordValue | quote }}
  {{- if and (not .Values.config.postgres.connectionStringSecretName) .Values.config.postgres.connectionString }}
  {{ .Values.config.postgres.connectionStringSecretKey | default "DATABASE_URL" }}: {{ .Values.config.postgres.connectionString | quote }}
  {{- end }}
{{ end }}
