config:
  existingSecret: ""
  domainName: "journal.k8s-lan.alcatrash.net"
  environment: "production"
  # Example external PostgreSQL configuration sourced from an existing Secret:
  # postgres:
  #   connectionString: "postgresql://db.example.com:5432/journiv"
  #   secretName: "my-db-secret"
  #   usernameKey: "username"
  #   passwordKey: "password"

ingress:
  enabled: true
  className: "traefik-internal"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: journal.k8s-lan.alcatrash.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: journal-k8s-lan-alcatrash-net-tls
      hosts:
        - journal.k8s-lan.alcatrash.net

postgresql:
  auth:
    password: ""
